---
# LootCrate v1.0.0 by Sean_M Config

# How often the Crate will spawn in seconds:
time: 30

# Crate spawn position:
"x": 147
"y": 31
"z": 120

# SOON
# Amount of items the Crate will have:
# items: 1

# Items the Crate can have:
contents: DIAMOND_SWORD
...
