---
# LootCrate 1.0.0 Config

# How often the Crate will spawn in seconds:
time: 60

# Crate spawn position:
x: 128
y: 4
z: 128

# Amount of items the Crate will have:
items: 1

# Items the Crate can have:
contents: 57
...
